import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const brigestaFont = localFont({
  src: '../public/fonts/brigesta.ttf',
  variable: '--font-local-brigesta',
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={`${brigestaFont.variable} h-full antialiased`}>
      <body className='mx-auto flex h-screen max-w-120 flex-col'>
        {children}
      </body>
    </html>
  )
}
